name: car_rental_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  shimmer:
  flutter_bloc:
  bloc:
  flutter_svg:
  flutter_gen:
  animate_do:
  app_bar_with_search_switch:
  pinput:
  carousel_slider:
  smooth_page_indicator:
  flutter_3d_controller:
  firebase_core:
  firebase_auth:
  google_sign_in:
  cloud_firestore:
  intl:
  url_launcher:
  equatable:
  table_calendar:
  firebase_storage:
  image_picker:
  uuid:
  flutter_local_notifications: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

  flutter_lints: ^4.0.0

flutter_gen:
  output: lib/core/gen
  line_length: 80

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/onboarding/
    - assets/images/flags/
    - assets/images/
    - assets/icons/
    - assets/3d-models/

  fonts:
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
