// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2FWjofbl-j34FXf3ij-kdRGjd_palbPc',
    appId: '1:332266405888:web:28fc441932acd53ce858e5',
    messagingSenderId: '332266405888',
    projectId: 'sakalwheelz',
    authDomain: 'sakalwheelz.firebaseapp.com',
    storageBucket: 'sakalwheelz.firebasestorage.app',
    measurementId: 'G-YCH2SW1RBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcR6HSFMNjAZexvRShDkSVxquGbrbvaJ0',
    appId: '1:332266405888:android:7efa35998c2d5403e858e5',
    messagingSenderId: '332266405888',
    projectId: 'sakalwheelz',
    storageBucket: 'sakalwheelz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbDZ6FmtQ7KsXfMVP7X2Gi0i031hAzIzM',
    appId: '1:332266405888:ios:4a4ed8bb0ab14e7ee858e5',
    messagingSenderId: '332266405888',
    projectId: 'sakalwheelz',
    storageBucket: 'sakalwheelz.firebasestorage.app',
    iosClientId: '332266405888-mpg4l4ojt4298bam6m6cte50hqkd8bhd.apps.googleusercontent.com',
    iosBundleId: 'com.car.rental.app.carRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbDZ6FmtQ7KsXfMVP7X2Gi0i031hAzIzM',
    appId: '1:332266405888:ios:4a4ed8bb0ab14e7ee858e5',
    messagingSenderId: '332266405888',
    projectId: 'sakalwheelz',
    storageBucket: 'sakalwheelz.firebasestorage.app',
    iosClientId: '332266405888-mpg4l4ojt4298bam6m6cte50hqkd8bhd.apps.googleusercontent.com',
    iosBundleId: 'com.car.rental.app.carRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2FWjofbl-j34FXf3ij-kdRGjd_palbPc',
    appId: '1:332266405888:web:72b26b04d14e1dd3e858e5',
    messagingSenderId: '332266405888',
    projectId: 'sakalwheelz',
    authDomain: 'sakalwheelz.firebaseapp.com',
    storageBucket: 'sakalwheelz.firebasestorage.app',
    measurementId: 'G-GDCH64WXQV',
  );
}
